services:
  auth-service:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
    container_name: transcribe-auth
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./transcribe-auth/app:/code/app
    networks:
      - transcribe-network
    restart: unless-stopped


networks:
  transcribe-network:
    driver: bridge